sudo: false
language: node_js
node_js:
  - '5'
  - '4'
  - '0.12'
before_script:
  - npm install -g grunt-cli
matrix:
  fast_finish: true
notifications:
  email:
    on_success: never
    on_failure: always
